name: build kernel on dispatch

on:
  workflow_dispatch:
    inputs:
      KERNEL_TREE:
        description: 'kernel tree'
        required: true
        default: ''
      KERNEL_TREE_BRANCH:
        description: 'kernel tree branch'
        required: true
        default: ''
      DEFCONFIG:
        description: 'defconfig'
        required: true
        default: '_defconfig'
      COMPILER:
        description: 'compiler (the toolchain)'
        required: true
        default: 'neutron-clang/latest'
      RELEASE_NAME:
        description: 'release name'
        required: true
        default: ''
      IMAGE:
        description: 'image'
        required: true
        default: 'Image.gz-dtb'
      ZIPPER:
        description: 'zipper (anykernel3 template)'
        required: true
        default: 'osm0sis/AnyKernel3'
      ZIPPER_BRANCH:
        description: 'zipper branch'
        required: true
        default: 'master'
      PYTHON_VERSION:
        description: 'python ver'
        required: true
        default: '3'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: display params
      run: |
        echo "::group::user env variables"
        echo "kernel tree: ${{ github.event.inputs.KERNEL_TREE }}"
        echo "kernel tree branch: ${{ github.event.inputs.KERNEL_TREE_BRANCH }}"
        echo "defconfig: ${{ github.event.inputs.DEFCONFIG }}"
        echo "compiler: ${{ github.event.inputs.COMPILER }}"
        echo "release name: ${{ github.event.inputs.RELEASE_NAME }}"
        echo "image: ${{ github.event.inputs.IMAGE }}"
        echo "zipper: ${{ github.event.inputs.ZIPPER }}"
        echo "zipper branch: ${{ github.event.inputs.ZIPPER_BRANCH }}"
        echo "python ver: ${{ github.event.inputs.PYTHON_VERSION }}"
        echo "::endgroup::"
    - name: checkout kernel source
      uses: actions/checkout@v3
      with:
        repository: ${{ github.event.inputs.KERNEL_TREE }}
        ref: ${{ github.event.inputs.KERNEL_TREE_BRANCH }}

    - name: checkout zipper
      uses: actions/checkout@v3
      with:
        repository: ${{ github.event.inputs.ZIPPER }}
        ref: ${{ github.event.inputs.ZIPPER_BRANCH }}
        path: zipper

    - name: export python ver to env
      run: echo PYTHON_VERSION=${{ github.event.inputs.PYTHON_VERSION }} >> $GITHUB_ENV

    - name: nuke some packages
      run: |
        sudo apt-fast update -qy
        sudo apt purge podman buildah skopeo temurin-*-jdk adoptium-ca-certificates openjdk-* ant ant-optional postgresql-* libpq-dev libmysqlclient* msodbcsql* mssql-tools unixodbc-dev mysql-client* mysql-common mysql-server* php*-*sql sphinxsearch mongodb* firefox google-chrome-stable microsoft-edge-stable xvfb apache2 apache2-* nginx nginx-* php-* php7* php8* session-manager-plugin azure-cli google-cloud-sdk gh subversion mercurial vim vim-* dotnet* aspnetcore* mono-* mono* libmono-* libmono* monodoc* msbuild nuget ruby* rake ri g++-9 g++-10 g++-12 gcc-9 gcc-10 gcc-12 gfortran-* clang-* libclang* llvm-* libllvm* lldb-* lld-* clang-format-* clang-tidy-* powershell r-base* r-cran* r-doc* r-recommended snapd man-db manpages libgtk-3-* ubuntu-mono *-icon-theme imagemagick imagemagick-6-common libgl1-mesa-dri firebird*
        sudo apt autopurge

    - name: Android kernel build
      uses: fukiame/android-kernel-actions@master
      id: build
      env:
        NAME: ${{ github.event.inputs.RELEASE_NAME }}
      with:
        arch: arm64
        compiler: ${{ github.event.inputs.COMPILER }}
        defconfig: ${{ github.event.inputs.DEFCONFIG }}
        image: ${{ github.event.inputs.IMAGE }}

    - name: release build
      uses: ncipollo/release-action@v1
      with:
        artifacts: ${{ steps.build.outputs.outfile }}
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.run_number }}
